# Generated by Django 4.2.6 on 2023-10-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("url", models.URLField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("price_usd", models.IntegerField()),
                ("odometer", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=13)),
                ("image_url", models.ImageField(upload_to="")),
                ("images_count", models.IntegerField()),
                ("car_number", models.CharField(max_length=255, null=True)),
                ("car_vin", models.CharField(max_length=255, null=True)),
                ("datetime_found", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
